name = "HTTP"
grammar = "http"
path_suffixes = ["http", "rest"]
line_comments = ["#", "//"]

brackets = [
    { start = "\"", end = "\"", close = true, newline = false },
    { start = "{", end = "}", close = true, newline = false },
    { start = "[", end = "]", close = true, newline = false },
    { start = "<", end = ">", close = true, newline = false },
]
