id = "http-client"
name = "HTTP Client"
version = "0.1.0"
schema_version = 1
description = "Run .http and .rest requests from Zed with curl-backed language tasks."
repository = "https://github.com/gozenc/zed-http-client"
authors = ["fgoezenc"]
themes = []
languages = ["languages/http"]

[lib]
kind = "Rust"
version = "0.7.0"

[grammars.http]
repository = "https://github.com/gozenc/zed-http-client"
rev = "2a347cc0deec0b3211dd8f6ffa6ea1eebb5502b2"
path = "vendor/http-grammar"

[language_servers]

[slash_commands]

[indexed_docs_providers]
